services:
  app:
    build: .
    container_name: funzika_app
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      funzika_net:
        ipv4_address: 10.0.0.3

  db:
    image: mysql:8.0
    container_name: funzika_db
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      funzika_net:
        ipv4_address: 10.0.0.2

  nginx:
    image: nginx:latest
    container_name: funzika_nginx
    ports:
      - "8081:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      funzika_net:
        ipv4_address: 10.0.0.4

volumes:
  mysql_data:

networks:
  funzika_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
