"""Added cascade delete to quiz-question relationship

Revision ID: 0415595d5509
Revises: ca7ee09a9cac
Create Date: 2025-01-02 14:38:00.615194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0415595d5509'
down_revision = 'ca7ee09a9cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint('questions_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'quizzes', ['quiz_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('questions_ibfk_1', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
